name: Reetika Sachdeva
markdown: redcarpet
timezone: America/New_York
highlighter: pygments
permalink: pretty
gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      author: "Reetika"
